// styling 
import './globals.css'


// components
import SideMenu from '@/components/SideMenu/SideMenu'
import CreateFoodModal from '@/components/Modals/CreateFoodItem/CreateFoodItemModal'
import TransitionClientElement from '@/components/Transition/TransitionClientElement'
import MainMenu from '@/components/SideMenu/MainMenu'

export const metadata = {
  title: 'Nourish',
  description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className='flex flex-col bg-slate-100 w-full h-auto'>
        
          {/* <SupabaseProvider> */}
          <MainMenu />
          <SideMenu />
            {children}
          {/* </SupabaseProvider> */}
      </body>
    </html>
  )
}
