import Header from '@/components/Header'
import SideMenu from '@/components/SideMenu/SideMenu'
import './globals.css'
import CreateFoodModal from '@/components/Modals/CreateFoodItem/CreateFoodItemModal'

export const metadata = {
  title: 'Nourish',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className='flex flex-col bg-slate-100 w-full h-full'>
        <Header />
          {/* <SupabaseProvider> */}
          <CreateFoodModal />
          <SideMenu />
            {children}
          {/* </SupabaseProvider> */}
      </body>
    </html>
  )
}
